### PR TITLE
Add support for OCCT variants novtk/all

### PR DESCRIPTION
**Pull request by Krande**
This PR adds support for occt variants (all & novtk). The latter is convenient when you need fewest possible package dependencies and you are not relying on any VTK features compiled in occt.

### CODE REVIEW

**Comment by Krande** [comment]
@conda-forge-admin, please rerender

**Comment by Krande** [comment]
@tpaviot On my end http://pythonocc.org redirects to "https://serp.ai/python-courses/". 

Does that happen to you too? Might I suggest we change the "home" link to https://github.com/tpaviot/pythonocc-core in the meta.yaml "about" section?

```yaml
about:
  home: http://www.pythonocc.org/ -> https://github.com/tpaviot/pythonocc-core
```

**Comment by tpaviot** [comment]
> @tpaviot On my end http://pythonocc.org redirects to "https://serp.ai/python-courses/".
> 
> Does that happen to you too? Might I suggest we change the "home" link to https://github.com/tpaviot/pythonocc-core in the meta.yaml "about" section?
> 
> ```yaml
> about:
>   home: http://www.pythonocc.org/ -> https://github.com/tpaviot/pythonocc-core
> ```

Yes, home points to pythonocc-core gh page

**Comment by Krande** [comment]
@looooo Let me know if you have any thoughts on this? And if you agree, I think this should be ready for merging :)

**Comment by looooo** [comment]
Thanks @Krande, I think it's fine to merge this.

**Pull request merged**
