### PR TITLE
6.7.2

### PR DESCRIPTION
**Pull request by looooo**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by tpaviot** [comment]
@looooo the sha256 sum is not correct, it should be ```84b1dad3b262027efc3314ab1f7cc8167ac353a1ffeea081e741e4c60319b848```

**Comment by tpaviot** [comment]
@looooo ```numpy``` is a requirement, sorry for not documenting this critical change, it seems to be missing and causing a failure on linux

**Comment by tpaviot** [comment]
@looooo occt-7.6.2 conda-forge is built without tbb support, tbb-devel dependency on pythonocc-core will have no effect unless occt-7.6.2 is updated

**Comment by tpaviot** [comment]
The numpy version must be >= 1.17 (see conda recipe for pythonocc)

**Comment by tpaviot** [comment]
@looooo There is still one missing depency (run only): svgwrite

In the build script, you must add ```-DPYTHONOCC_MESHDS_NUMPY=ON```

**Comment by looooo** [comment]
@conda-forge-admin, please rerender

**Comment by tpaviot** [comment]
@looooo well, I'm not familiar with the conda-forge build process, at least much less familiar than you are. It's ok like this for me, no need to be added as a maintainer

**Comment by tpaviot** [comment]
so far only the arm64 seems to be failing, good progress!

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by tpaviot** [comment]
:+1: 
@looooo  The current status of the python wrapper is ready for occt-7.6.3, feel free to open a new ticker on the pythonocc issue tracker as soon as the conda-forge package for occt763 is ready

**Pull request merged**
