### PR TITLE
add PR for v7.7.2 of pyocc core

### PR DESCRIPTION
**Pull request by Krande**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Now that there's a [7.7.2 release](https://github.com/tpaviot/pythonocc-core/releases/tag/7.7.2) in pythonocc-core I suggest we update the meta?

### CODE REVIEW

**Comment by Krande** [comment]
@conda-forge-admin, please rerender

**Comment by Krande** [comment]
@looooo I think this is ready for merging :) Let me know if you have any questions or comments?

**Comment by tpaviot** [comment]
Everything is looking good indeed :+1:

**Comment by tpaviot** [comment]
@looooo can you plase merge this pr?

**Comment by looooo** [comment]
Thanks

**Pull request merged**
